from __future__ import annotations

from pathlib import Path

from diskanalysis.config.schema import AppConfig, PatternRule
from diskanalysis.models.enums import InsightCategory


def default_config() -> AppConfig:
    home = str(Path.home())

    temp_patterns = [
        PatternRule(
            "System Temp",
            "**/tmp/**",
            InsightCategory.TEMP,
            True,
            "rm -rf /tmp/<target>",
        ),
        PatternRule(
            "User Temp",
            "**/.tmp/**",
            InsightCategory.TEMP,
            True,
            "Clean temporary workspace files",
        ),
        PatternRule(
            "Log Files",
            "**/*.log",
            InsightCategory.TEMP,
            True,
            "Archive or delete stale logs",
            "file",
        ),
        PatternRule(
            "Python Bytecode",
            "**/__pycache__/**",
            InsightCategory.TEMP,
            True,
            "python -m compileall <project>",
        ),
        PatternRule(
            "Pytest Cache",
            "**/.pytest_cache/**",
            InsightCategory.TEMP,
            True,
            "pytest --cache-clear",
        ),
        PatternRule(
            "Mypy Cache",
            "**/.mypy_cache/**",
            InsightCategory.TEMP,
            True,
            "mypy --cache-dir /tmp/mypy",
        ),
        PatternRule(
            "Ruff Cache",
            "**/.ruff_cache/**",
            InsightCategory.TEMP,
            True,
            "ruff clean",
        ),
        PatternRule(
            "Coverage Files",
            "**/.coverage*",
            InsightCategory.TEMP,
            True,
            "coverage erase",
        ),
        PatternRule(
            "Editor Swaps",
            "**/*.{swp,swo,tmp,bak}",
            InsightCategory.TEMP,
            True,
            "Delete editor swap files",
            "file",
        ),
        PatternRule(
            "macOS Metadata",
            "**/.DS_Store",
            InsightCategory.TEMP,
            True,
            "find . -name .DS_Store -delete",
            "file",
        ),
        PatternRule(
            "npm Logs",
            "**/npm-debug.log*",
            InsightCategory.TEMP,
            True,
            "Delete npm debug logs",
            "file",
        ),
        PatternRule(
            "Yarn Logs",
            "**/yarn-error.log*",
            InsightCategory.TEMP,
            True,
            "Delete yarn error logs",
            "file",
        ),
        PatternRule(
            "Crash Reports",
            "**/Library/Application Support/CrashReporter/**",
            InsightCategory.TEMP,
            True,
            "Delete old crash reports",
        ),
        PatternRule(
            "SQLite Journals",
            "**/*.db-journal",
            InsightCategory.TEMP,
            True,
            "SQLite journal files, safe to delete when DB is not open",
            "file",
        ),
        PatternRule(
            "Terraform State Backups",
            "**/*.tfstate.backup",
            InsightCategory.TEMP,
            True,
            "Terraform state backups; verify remote state is current",
            "file",
        ),
    ]

    cache_patterns = [
        # ── Package managers ──
        PatternRule(
            "npm Cache",
            "**/.npm/**",
            InsightCategory.CACHE,
            True,
            "npm cache clean --force",
        ),
        PatternRule(
            "Yarn Cache",
            "**/.cache/yarn/**",
            InsightCategory.CACHE,
            True,
            "yarn cache clean",
        ),
        PatternRule(
            "pnpm Store",
            "**/.pnpm-store/**",
            InsightCategory.CACHE,
            True,
            "pnpm store prune",
        ),
        PatternRule(
            "pip Cache",
            "**/.cache/pip/**",
            InsightCategory.CACHE,
            True,
            "pip cache purge",
        ),
        PatternRule(
            "uv Cache",
            "**/.cache/uv/**",
            InsightCategory.CACHE,
            True,
            "uv cache clean",
        ),
        PatternRule(
            "poetry Cache",
            "**/.cache/pypoetry/**",
            InsightCategory.CACHE,
            True,
            "poetry cache clear pypi --all",
        ),
        PatternRule(
            "conda Packages",
            "**/.conda/pkgs/**",
            InsightCategory.CACHE,
            True,
            "conda clean --all",
        ),
        PatternRule(
            "Homebrew Cache",
            "**/Library/Caches/Homebrew/**",
            InsightCategory.CACHE,
            True,
            "brew cleanup",
        ),
        PatternRule(
            "NuGet Cache",
            "**/.nuget/packages/**",
            InsightCategory.CACHE,
            True,
            "dotnet nuget locals all --clear",
        ),
        PatternRule(
            "Composer Cache",
            "**/.composer/cache/**",
            InsightCategory.CACHE,
            True,
            "composer clear-cache",
        ),
        PatternRule(
            "Bundler Cache",
            "**/.bundle/cache/**",
            InsightCategory.CACHE,
            True,
            "bundle clean --force",
        ),
        # ── JVM ecosystem ──
        PatternRule(
            "Gradle Cache",
            "**/.gradle/**",
            InsightCategory.CACHE,
            True,
            "gradle --stop && rm -rf ~/.gradle/caches",
        ),
        PatternRule(
            "Maven Repo",
            "**/.m2/repository/**",
            InsightCategory.CACHE,
            False,
            "Review dependencies before deletion",
        ),
        PatternRule(
            "Ivy Cache",
            "**/.ivy2/cache/**",
            InsightCategory.CACHE,
            True,
            "rm -rf ~/.ivy2/cache",
        ),
        PatternRule(
            "SBT Boot",
            "**/.sbt/**",
            InsightCategory.CACHE,
            True,
            "rm -rf ~/.sbt/boot",
        ),
        PatternRule(
            "Coursier Cache",
            "**/.cache/coursier/**",
            InsightCategory.CACHE,
            True,
            "cs cache --help",
        ),
        # ── Rust / Go / Native ──
        PatternRule(
            "Cargo Registry",
            "**/.cargo/registry/**",
            InsightCategory.CACHE,
            True,
            "cargo cache -a",
        ),
        PatternRule(
            "rustup Downloads",
            "**/.rustup/downloads/**",
            InsightCategory.CACHE,
            True,
            "rustup self cleanup",
        ),
        PatternRule(
            "Go Module Cache",
            "**/go/pkg/mod/**",
            InsightCategory.CACHE,
            True,
            "go clean -modcache",
        ),
        PatternRule(
            "Go Build Cache",
            "**/.cache/go-build/**",
            InsightCategory.CACHE,
            True,
            "go clean -cache",
        ),
        # ── JS build tool caches ──
        PatternRule(
            "Turbo Cache",
            "**/.turbo/**",
            InsightCategory.CACHE,
            True,
            "turbo prune or delete .turbo",
        ),
        PatternRule(
            "Parcel Cache",
            "**/.parcel-cache/**",
            InsightCategory.CACHE,
            True,
            "Parcel will regenerate on build",
        ),
        PatternRule(
            "Node GYP",
            "**/.node-gyp/**",
            InsightCategory.CACHE,
            True,
            "npm cache clean --force",
        ),
        # ── Apple / Xcode ──
        PatternRule(
            "Xcode DerivedData",
            "**/Library/Developer/Xcode/DerivedData/**",
            InsightCategory.CACHE,
            True,
            "Delete Xcode DerivedData",
        ),
        PatternRule(
            "iOS Simulator",
            "**/Library/Developer/CoreSimulator/**",
            InsightCategory.CACHE,
            False,
            "Remove unused simulators from Xcode",
        ),
        # ── Containers / Infra ──
        PatternRule(
            "Docker Layers",
            "**/Library/Containers/com.docker.docker/**",
            InsightCategory.CACHE,
            False,
            "docker system prune",
        ),
        PatternRule(
            "Kube Cache",
            "**/.kube/cache/**",
            InsightCategory.CACHE,
            True,
            "Delete kube cache",
        ),
        PatternRule(
            "Terraform Plugins",
            "**/.terraform/**",
            InsightCategory.CACHE,
            True,
            "rm -rf .terraform && terraform init",
        ),
        PatternRule(
            "Ansible Temp",
            "**/.ansible/tmp/**",
            InsightCategory.CACHE,
            True,
            "Ansible will regenerate",
        ),
        # ── AI / ML model caches ──
        PatternRule(
            "HuggingFace Cache",
            "**/.cache/huggingface/**",
            InsightCategory.CACHE,
            False,
            "Review model cache before deleting",
        ),
        PatternRule(
            "PyTorch Cache",
            "**/.cache/torch/**",
            InsightCategory.CACHE,
            False,
            "Review model cache before deleting",
        ),
        PatternRule(
            "Whisper Cache",
            "**/.cache/whisper/**",
            InsightCategory.CACHE,
            False,
            "Review model cache before deleting",
        ),
        PatternRule(
            "Ollama Models",
            "**/.ollama/**",
            InsightCategory.CACHE,
            False,
            "ollama rm <model>",
        ),
        # ── Linters / pre-commit ──
        PatternRule(
            "pre-commit Cache",
            "**/.cache/pre-commit/**",
            InsightCategory.CACHE,
            True,
            "pre-commit clean",
        ),
        # ── Browsers ──
        PatternRule(
            "Chrome Cache",
            "**/Library/Caches/Google/Chrome/**",
            InsightCategory.CACHE,
            True,
            "Clear browser cache from settings",
        ),
        PatternRule(
            "Firefox Cache",
            "**/.cache/mozilla/firefox/**",
            InsightCategory.CACHE,
            True,
            "Clear Firefox cache",
        ),
        PatternRule(
            "Safari Cache",
            "**/Library/Caches/com.apple.Safari/**",
            InsightCategory.CACHE,
            True,
            "Clear Safari cache from settings",
        ),
        # ── IDEs / Editors ──
        PatternRule(
            "JetBrains Cache",
            "**/Library/Caches/JetBrains/**",
            InsightCategory.CACHE,
            True,
            "Invalidate IDE caches",
        ),
        PatternRule(
            "JetBrains Logs",
            "**/Library/Logs/JetBrains/**",
            InsightCategory.CACHE,
            True,
            "Delete IDE log files",
        ),
        PatternRule(
            "VSCode Cache",
            "**/Library/Application Support/Code/Cache/**",
            InsightCategory.CACHE,
            True,
            "Clear VSCode cache",
        ),
    ]

    build_artifact_patterns = [
        # ── JS / Node ──
        PatternRule(
            "node_modules",
            "**/node_modules/**",
            InsightCategory.BUILD_ARTIFACT,
            True,
            "npm install",
            stop_recursion=True,
        ),
        PatternRule(
            "Bower Components",
            "**/bower_components/**",
            InsightCategory.BUILD_ARTIFACT,
            True,
            "bower install",
            stop_recursion=True,
        ),
        PatternRule(
            "Next.js build",
            "**/.next/**",
            InsightCategory.BUILD_ARTIFACT,
            True,
            "next build",
            stop_recursion=True,
        ),
        PatternRule(
            "Nuxt build",
            "**/.nuxt/**",
            InsightCategory.BUILD_ARTIFACT,
            True,
            "nuxt build",
            stop_recursion=True,
        ),
        # ── Python ──
        PatternRule(
            "Python venv",
            "**/.venv/**",
            InsightCategory.BUILD_ARTIFACT,
            False,
            "Recreate with uv venv .venv",
            stop_recursion=True,
        ),
        PatternRule(
            "Python venv",
            "**/venv/**",
            InsightCategory.BUILD_ARTIFACT,
            False,
            "python -m venv venv",
            stop_recursion=True,
        ),
        PatternRule(
            "Python cache",
            "**/__pycache__/**",
            InsightCategory.BUILD_ARTIFACT,
            True,
            "Regenerated on run",
            stop_recursion=True,
        ),
        PatternRule(
            "Python Egg Info",
            "**/*.egg-info",
            InsightCategory.BUILD_ARTIFACT,
            True,
            "pip install -e . to regenerate",
            apply_to="dir",
            stop_recursion=True,
        ),
        PatternRule(
            "tox env",
            "**/.tox/**",
            InsightCategory.BUILD_ARTIFACT,
            True,
            "tox -r",
            stop_recursion=True,
        ),
        # ── Generic build outputs ──
        PatternRule(
            "Build dir",
            "**/build/**",
            InsightCategory.BUILD_ARTIFACT,
            True,
            "Re-run build command",
            stop_recursion=True,
        ),
        PatternRule(
            "Dist dir",
            "**/dist/**",
            InsightCategory.BUILD_ARTIFACT,
            True,
            "Re-run package build",
            stop_recursion=True,
        ),
        PatternRule(
            "Object files",
            "**/obj/**",
            InsightCategory.BUILD_ARTIFACT,
            True,
            "dotnet build",
            stop_recursion=True,
        ),
        PatternRule(
            "Binary output",
            "**/bin/**",
            InsightCategory.BUILD_ARTIFACT,
            True,
            "Rebuild binaries",
            stop_recursion=True,
        ),
        PatternRule(
            "Coverage artifacts",
            "**/coverage/**",
            InsightCategory.BUILD_ARTIFACT,
            True,
            "Run tests again for coverage",
            stop_recursion=True,
        ),
        # ── Native / compiled languages ──
        PatternRule(
            "Rust target",
            "**/target/**",
            InsightCategory.BUILD_ARTIFACT,
            True,
            "cargo build",
            stop_recursion=True,
        ),
        PatternRule(
            "Swift build",
            "**/.build/**",
            InsightCategory.BUILD_ARTIFACT,
            True,
            "swift build",
            stop_recursion=True,
        ),
        PatternRule(
            "CMake build",
            "**/CMakeFiles/**",
            InsightCategory.BUILD_ARTIFACT,
            True,
            "Re-run cmake",
            stop_recursion=True,
        ),
        PatternRule(
            "Zig cache",
            "**/zig-cache/**",
            InsightCategory.BUILD_ARTIFACT,
            True,
            "zig build",
            stop_recursion=True,
        ),
        # ── .NET / NuGet ──
        PatternRule(
            "NuGet packages",
            "**/packages/**",
            InsightCategory.BUILD_ARTIFACT,
            True,
            "dotnet restore",
            stop_recursion=True,
        ),
    ]

    custom_patterns = [
        PatternRule(
            "Archive files",
            "**/*.{zip,tar,gz,7z,dmg,iso}",
            InsightCategory.CUSTOM,
            False,
            "Archive files may be backup artifacts; verify before removing.",
            apply_to="file",
        ),
        PatternRule(
            "Database Dumps",
            "**/*.{sql,dump,dmp}",
            InsightCategory.CUSTOM,
            False,
            "Database dump; verify it is not a needed backup before removing.",
            apply_to="file",
        ),
        PatternRule(
            "VM Disk Images",
            "**/*.{vmdk,vdi,qcow2}",
            InsightCategory.CUSTOM,
            False,
            "Virtual machine disk image; review before removing.",
            apply_to="file",
        ),
        PatternRule(
            "Core Dumps",
            "**/core.*",
            InsightCategory.CUSTOM,
            True,
            "Core dump file; safe to delete after debugging.",
            apply_to="file",
        ),
    ]

    return AppConfig(
        additional_temp_paths=[
            f"{home}/Library/Caches/TemporaryItems",
            f"{home}/.Trash",
        ],
        additional_cache_paths=[f"{home}/.cache"],
        temp_patterns=temp_patterns,
        cache_patterns=cache_patterns,
        build_artifact_patterns=build_artifact_patterns,
        custom_patterns=custom_patterns,
        follow_symlinks=False,
        max_depth=None,
        scan_workers=4,
        summary_top_count=15,
        page_size=100,
        max_insights_per_category=1000,
        overview_top_folders=100,
        scroll_step=20,
    )
