from __future__ import annotations

from pathlib import Path
from typing import Literal

from diskanalysis.config.schema import AppConfig, PatternRule, Thresholds
from diskanalysis.models.enums import InsightCategory


def _rule(
    name: str,
    pattern: str,
    category: InsightCategory,
    safe_to_delete: bool,
    recommendation: str,
    apply_to: Literal["file", "dir", "both"] = "both",
    stop_recursion: bool = False,
) -> PatternRule:
    return PatternRule(
        name=name,
        pattern=pattern,
        category=category,
        safe_to_delete=safe_to_delete,
        recommendation=recommendation,
        apply_to=apply_to,
        stop_recursion=stop_recursion,
    )


def default_config() -> AppConfig:
    home = str(Path.home())

    temp_patterns = [
        _rule(
            "System Temp",
            "**/tmp/**",
            InsightCategory.TEMP,
            True,
            "rm -rf /tmp/<target>",
        ),
        _rule(
            "User Temp",
            "**/.tmp/**",
            InsightCategory.TEMP,
            True,
            "Clean temporary workspace files",
        ),
        _rule(
            "Log Files",
            "**/*.log",
            InsightCategory.TEMP,
            True,
            "Archive or delete stale logs",
            "file",
        ),
        _rule(
            "Python Bytecode",
            "**/__pycache__/**",
            InsightCategory.TEMP,
            True,
            "python -m compileall <project>",
        ),
        _rule(
            "Pytest Cache",
            "**/.pytest_cache/**",
            InsightCategory.TEMP,
            True,
            "pytest --cache-clear",
        ),
        _rule(
            "Mypy Cache",
            "**/.mypy_cache/**",
            InsightCategory.TEMP,
            True,
            "mypy --cache-dir /tmp/mypy",
        ),
        _rule(
            "Ruff Cache",
            "**/.ruff_cache/**",
            InsightCategory.TEMP,
            True,
            "ruff clean",
        ),
        _rule(
            "Coverage Files",
            "**/.coverage*",
            InsightCategory.TEMP,
            True,
            "coverage erase",
        ),
        _rule(
            "Editor Swaps",
            "**/*.{swp,swo,tmp,bak}",
            InsightCategory.TEMP,
            True,
            "Delete editor swap files",
            "file",
        ),
        _rule(
            "macOS Metadata",
            "**/.DS_Store",
            InsightCategory.TEMP,
            True,
            "find . -name .DS_Store -delete",
            "file",
        ),
        _rule(
            "npm Logs",
            "**/npm-debug.log*",
            InsightCategory.TEMP,
            True,
            "Delete npm debug logs",
            "file",
        ),
        _rule(
            "Yarn Logs",
            "**/yarn-error.log*",
            InsightCategory.TEMP,
            True,
            "Delete yarn error logs",
            "file",
        ),
    ]

    cache_patterns = [
        _rule(
            "npm Cache",
            "**/.npm/**",
            InsightCategory.CACHE,
            True,
            "npm cache clean --force",
        ),
        _rule(
            "Yarn Cache",
            "**/.cache/yarn/**",
            InsightCategory.CACHE,
            True,
            "yarn cache clean",
        ),
        _rule(
            "pnpm Store",
            "**/.pnpm-store/**",
            InsightCategory.CACHE,
            True,
            "pnpm store prune",
        ),
        _rule(
            "pip Cache",
            "**/.cache/pip/**",
            InsightCategory.CACHE,
            True,
            "pip cache purge",
        ),
        _rule(
            "uv Cache",
            "**/.cache/uv/**",
            InsightCategory.CACHE,
            True,
            "uv cache clean",
        ),
        _rule(
            "poetry Cache",
            "**/.cache/pypoetry/**",
            InsightCategory.CACHE,
            True,
            "poetry cache clear pypi --all",
        ),
        _rule(
            "conda Packages",
            "**/.conda/pkgs/**",
            InsightCategory.CACHE,
            True,
            "conda clean --all",
        ),
        _rule(
            "NuGet Cache",
            "**/.nuget/packages/**",
            InsightCategory.CACHE,
            True,
            "dotnet nuget locals all --clear",
        ),
        _rule(
            "Gradle Cache",
            "**/.gradle/**",
            InsightCategory.CACHE,
            True,
            "gradle --stop && rm -rf ~/.gradle/caches",
        ),
        _rule(
            "Maven Repo",
            "**/.m2/repository/**",
            InsightCategory.CACHE,
            False,
            "Review dependencies before deletion",
        ),
        _rule(
            "Ivy Cache",
            "**/.ivy2/cache/**",
            InsightCategory.CACHE,
            True,
            "rm -rf ~/.ivy2/cache",
        ),
        _rule(
            "SBT Boot",
            "**/.sbt/**",
            InsightCategory.CACHE,
            True,
            "rm -rf ~/.sbt/boot",
        ),
        _rule(
            "Coursier Cache",
            "**/.cache/coursier/**",
            InsightCategory.CACHE,
            True,
            "cs cache --help",
        ),
        _rule(
            "Cargo Registry",
            "**/.cargo/registry/**",
            InsightCategory.CACHE,
            True,
            "cargo cache -a",
        ),
        _rule(
            "rustup Downloads",
            "**/.rustup/downloads/**",
            InsightCategory.CACHE,
            True,
            "rustup self cleanup",
        ),
        _rule(
            "Go Module Cache",
            "**/go/pkg/mod/**",
            InsightCategory.CACHE,
            True,
            "go clean -modcache",
        ),
        _rule(
            "Composer Cache",
            "**/.composer/cache/**",
            InsightCategory.CACHE,
            True,
            "composer clear-cache",
        ),
        _rule(
            "Bundler Cache",
            "**/.bundle/cache/**",
            InsightCategory.CACHE,
            True,
            "bundle clean --force",
        ),
        _rule(
            "Xcode DerivedData",
            "**/Library/Developer/Xcode/DerivedData/**",
            InsightCategory.CACHE,
            True,
            "Delete Xcode DerivedData",
        ),
        _rule(
            "iOS Simulator",
            "**/Library/Developer/CoreSimulator/**",
            InsightCategory.CACHE,
            False,
            "Remove unused simulators from Xcode",
        ),
        _rule(
            "Docker Layers",
            "**/Library/Containers/com.docker.docker/**",
            InsightCategory.CACHE,
            False,
            "docker system prune",
        ),
        _rule(
            "Kube Cache",
            "**/.kube/cache/**",
            InsightCategory.CACHE,
            True,
            "Delete kube cache",
        ),
        _rule(
            "Terraform Plugins",
            "**/.terraform/**",
            InsightCategory.CACHE,
            True,
            "rm -rf .terraform && terraform init",
        ),
        _rule(
            "pre-commit Cache",
            "**/.cache/pre-commit/**",
            InsightCategory.CACHE,
            True,
            "pre-commit clean",
        ),
        _rule(
            "HuggingFace Cache",
            "**/.cache/huggingface/**",
            InsightCategory.CACHE,
            False,
            "Review model cache before deleting",
        ),
        _rule(
            "Ollama Models",
            "**/.ollama/**",
            InsightCategory.CACHE,
            False,
            "ollama rm <model>",
        ),
        _rule(
            "Chrome Cache",
            "**/Library/Caches/Google/Chrome/**",
            InsightCategory.CACHE,
            True,
            "Clear browser cache from settings",
        ),
        _rule(
            "Firefox Cache",
            "**/.cache/mozilla/firefox/**",
            InsightCategory.CACHE,
            True,
            "Clear Firefox cache",
        ),
        _rule(
            "JetBrains Cache",
            "**/Library/Caches/JetBrains/**",
            InsightCategory.CACHE,
            True,
            "Invalidate IDE caches",
        ),
        _rule(
            "VSCode Cache",
            "**/Library/Application Support/Code/Cache/**",
            InsightCategory.CACHE,
            True,
            "Clear VSCode cache",
        ),
    ]

    build_artifact_patterns = [
        _rule(
            "node_modules",
            "**/node_modules/**",
            InsightCategory.BUILD_ARTIFACT,
            True,
            "npm install",
            stop_recursion=True,
        ),
        _rule(
            "Python venv",
            "**/.venv/**",
            InsightCategory.BUILD_ARTIFACT,
            False,
            "Recreate with uv venv .venv",
            stop_recursion=True,
        ),
        _rule(
            "Python venv",
            "**/venv/**",
            InsightCategory.BUILD_ARTIFACT,
            False,
            "python -m venv venv",
            stop_recursion=True,
        ),
        _rule(
            "Build dir",
            "**/build/**",
            InsightCategory.BUILD_ARTIFACT,
            True,
            "Re-run build command",
            stop_recursion=True,
        ),
        _rule(
            "Dist dir",
            "**/dist/**",
            InsightCategory.BUILD_ARTIFACT,
            True,
            "Re-run package build",
            stop_recursion=True,
        ),
        _rule(
            "Object files",
            "**/obj/**",
            InsightCategory.BUILD_ARTIFACT,
            True,
            "dotnet build",
            stop_recursion=True,
        ),
        _rule(
            "Binary output",
            "**/bin/**",
            InsightCategory.BUILD_ARTIFACT,
            True,
            "Rebuild binaries",
            stop_recursion=True,
        ),
        _rule(
            "Rust target",
            "**/target/**",
            InsightCategory.BUILD_ARTIFACT,
            True,
            "cargo build",
            stop_recursion=True,
        ),
        _rule(
            "NuGet packages",
            "**/packages/**",
            InsightCategory.BUILD_ARTIFACT,
            True,
            "dotnet restore",
            stop_recursion=True,
        ),
        _rule(
            "Python cache",
            "**/__pycache__/**",
            InsightCategory.BUILD_ARTIFACT,
            True,
            "Regenerated on run",
            stop_recursion=True,
        ),
        _rule(
            "Next.js build",
            "**/.next/**",
            InsightCategory.BUILD_ARTIFACT,
            True,
            "next build",
            stop_recursion=True,
        ),
        _rule(
            "Nuxt build",
            "**/.nuxt/**",
            InsightCategory.BUILD_ARTIFACT,
            True,
            "nuxt build",
            stop_recursion=True,
        ),
        _rule(
            "Coverage artifacts",
            "**/coverage/**",
            InsightCategory.BUILD_ARTIFACT,
            True,
            "Run tests again for coverage",
            stop_recursion=True,
        ),
        _rule(
            "tox env",
            "**/.tox/**",
            InsightCategory.BUILD_ARTIFACT,
            True,
            "tox -r",
            stop_recursion=True,
        ),
    ]

    custom_patterns = [
        _rule(
            "Archive files",
            "**/*.{zip,tar,gz,7z,dmg,iso}",
            InsightCategory.CUSTOM,
            False,
            "Archive files may be backup artifacts; verify before removing.",
            apply_to="file",
        )
    ]

    return AppConfig(
        thresholds=Thresholds(),
        exclude_paths=["**/.git/**", "**/.hg/**", "**/.svn/**"],
        additional_temp_paths=[
            f"{home}/Library/Caches/TemporaryItems",
            f"{home}/.Trash",
        ],
        additional_cache_paths=[f"{home}/.cache"],
        temp_patterns=temp_patterns,
        cache_patterns=cache_patterns,
        build_artifact_patterns=build_artifact_patterns,
        custom_patterns=custom_patterns,
        follow_symlinks=False,
        max_depth=None,
        scan_workers=4,
        top_n=15,
    )
